`.gitignore`:
ignored reward outcome

---

`tools/peter-rl-training-v1.py`:

- changes some parameters in dict

- use single `pbar` instead.

- `plt` part has move to `main()`,
further debug is needed.

---

`tools/peter_detector.py`:

- fix the following naming error :

`set_save_sate()`
$\implies$
`set_save_state()`

`calculate_theta()`
$\implies$
`calculate_theta_current()`

- `combined` and `control`
becomes a member variable,
which is try to fix the following bug:

```bash
combined = np.zeros((self.win_height, self.win_width, 3), dtype=np.uint8)
numpy.core._exceptions.MemoryError: Unable to allocate 6.55 MiB for an array with shape (1080, 2120, 3) and data type uint8
```

- video writer has unstable `fps`
in multi-process task,
and it will be abandon in the future version!

---

`tools/peter_serial.py`:

- `amp`, `offset`, `omega`, `ratio`
become `str` instead of `int`

- changes some parameters in dict

---